### ISSUE TITLE
install.md改善案

### ISSUE THREAD

**Issue by nafuka11** [GuitarBuilderClass/Teaching-Assistant-Python#1]
## install.md
- `テストや競技プログラミングに使いたくなりそうな機能` は付録でも良いかもしれません。
  例えばPythonバージョン毎の機能として分けると、今後のオンラインジャッジのバージョン変更に対応しやすくなるかと。
- https://github.com/OptimisticPessimist/Teaching-Assistant-Python/blob/adac91c5e0c42c7940cddca6c65a26c27486a0d3/docs/install.md#L51
  空白が全角文字になっているため、番号つきリストの表示が崩れています。
- GitHubのアカウントの作成方法が書いてあると親切かも（記事へのリンク等）。
- コマンドはどこで入力するか説明が必要だと思います（Terminalを立ち上げるなど）。

**Comment by OptimisticPessimist** [comment]
> ## install.md
> * `テストや競技プログラミングに使いたくなりそうな機能` は付録でも良いかもしれません。
>   例えばPythonバージョン毎の機能として分けると、今後のオンラインジャッジのバージョン変更に対応しやすくなるかと。
-> 労力次第。。。

> * https://github.com/GuitarBuilderClass/Teaching-Assistant-Python/blob/adac91c5e0c42c7940cddca6c65a26c27486a0d3/docs/install.md#L51
>   
>   空白が全角文字になっているため、番号つきリストの表示が崩れています。
-> 修正

> * GitHubのアカウントの作成方法が書いてあると親切かも（記事へのリンク等）。
-> Qiita記事へリンク追加

> * コマンドはどこで入力するか説明が必要だと思います（Terminalを立ち上げるなど）。
-> 環境次第なので口頭説明（Vimでやるって言われたら僕は投げます）
